trigger:
- master
- qa
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'devops-microservice'
  AZURE_REGISTRY_URL: 'kfcregistry.azurecr.io'
  # Imagen Tag default (se configurará según la rama en los pasos)
  IMAGE_TAG: 'latest'  # Default value, se sobrescribirá en los pasos

jobs:
- job: BuildAndDeploy
  displayName: 'Build, Push and Deploy Docker Image'
  steps:

    # Paso para establecer el valor de IMAGE_TAG basado en la rama
    - script: |
        if [ "$(Build.SourceBranchName)" == "master" ]; then
          echo "##vso[task.setvariable variable=IMAGE_TAG]latest"
          echo "##vso[task.setvariable variable=DEPLOY]production-deployment"
          echo "##vso[task.setvariable variable=CONTAINER]production-container"
        elif [ "$(Build.SourceBranchName)" == "qa" ]; then
          echo "##vso[task.setvariable variable=IMAGE_TAG]qa"
          echo "##vso[task.setvariable variable=DEPLOY]qa-deployment"
          echo "##vso[task.setvariable variable=CONTAINER]qa-container"
        elif [ "$(Build.SourceBranchName)" == "dev" ]; then
          echo "##vso[task.setvariable variable=IMAGE_TAG]dev"
          echo "##vso[task.setvariable variable=DEPLOY]dev-deployment"
          echo "##vso[task.setvariable variable=CONTAINER]dev-container"
        fi
      displayName: 'Set IMAGE_TAG, DEPLOY, and CONTAINER based on branch'

    # Paso para construir la imagen Docker
    - task: Docker@2
      inputs:
        command: build
        repository: $(IMAGE_NAME)
        Dockerfile: 'Dockerfile'
        tags: |
          $(IMAGE_TAG)
      displayName: 'Build Docker Image'

    # Paso para empujar la imagen a ACR
    - task: Docker@2
      inputs:
        command: push
        repository: $(AZURE_REGISTRY_URL)/$(IMAGE_NAME)
        tags: |
          $(IMAGE_TAG)
        containerRegistry: 'SC_ACR_GRUPOKFC_DEV'
      displayName: 'Push image to ACR'

    # Paso para realizar el despliegue en función de la rama
    - script: |
        kubectl set image deployment/$(DEPLOY) $(CONTAINER)=$(AZURE_REGISTRY_URL)/$(IMAGE_NAME):$(IMAGE_TAG) --namespace=devops-microservice
      displayName: 'Update Kubernetes Deployment'
